# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hamming_filter_wrapper <- function(barcodes, read, threshold) {
    invisible(.Call('_BarcodeMatcher_hamming_filter_wrapper', PACKAGE = 'BarcodeMatcher', barcodes, read, threshold))
}

timesTwo <- function(x) {
    .Call('_BarcodeMatcher_timesTwo', PACKAGE = 'BarcodeMatcher', x)
}

